# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: newapp_dev
  pool: 5
  username: root
  password: da..
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: newapp_test
  pool: 5
  username: root
  password: da..
  socket: /var/run/mysqld/mysqld.sock